version: "3"

services:
  fdic_db:
    hostname: fdic_db
    image: mariadb:10.11.9
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=pass123
      - MARIADB_USER=user1
      - MARIADB_PASSWORD=nopass
    volumes:
      - fdic_db_data:/var/lib/mysql


volumes:
  fdic_db_data:

    
      


